feature: Support for multiple endpoints by chainID
vocdoni/census3 pull request #189
Opened 2024-04-08 10:04 UTC by lucasmenendez

- Includes an adaptation of https://github.com/vocdoni/vote-frame/blob/main/farcasterapi/web3/farcaster.go to handle multiple web3 endpoints by chain id.

Closes #73

2024-04-08 20:51 UTC, p4u requested changes
I'm not sure this PR adds the functionality discussed previously. Since it does not distribute the RPC requests by each call, but instead distributes clients.


Ideally, the networksManager would implement a type Client with the following interface (`networkmanager.Client(chainID)`):

```
// ContractCaller defines the methods needed to allow operating with a contract on a read
// only basis.
type ContractCaller interface {
	// CodeAt returns the code of the given account. This is needed to differentiate
	// between contract internal errors and the local chain being out of sync.
	CodeAt(ctx context.Context, contract common.Address, blockNumber *big.Int) ([]byte, error)

	// CallContract executes an Ethereum contract call with the specified data as the
	// input.
	CallContract(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error)
}
```

Then on each CodeAt or CallContract, behind the scenes, the networkManager chooses a different web3 endpoint from the list of working endpoints for such chainID.

erc721.NewERC721Contract() then receives the network manager client and the magic happens automatically. 

This is just an idea that tries to achieve the same functionality we have on the farcaster implementation. Feel free do discuss it.

PS: I think networksManager is a horrible name, web3pool or something like that would be more descriptive IMHO

2024-04-08 20:51 UTC, p4u commented on scanner/providers/web3/networks.go
> +func (nm *NetworksManager) URIsByChainID(chainID uint64) ([]string, bool) {
Rlock is missing

2024-04-08 20:51 UTC, p4u commented on scanner/providers/web3/networks.go
> +	shortNames := map[string]bool{}
Rlock() missing

2024-04-08 20:51 UTC, p4u commented on scanner/providers/web3/networks.go
> +	blockNumbers := make(map[uint64]uint64)
Rlock() missing

2024-04-09 12:12 UTC, lucasmenendez commented on scanner/providers/web3/web3_pool.go
> +			nm.networks[chainID][i].available = false
Okey, i think now i got it.

2024-04-11 14:51 UTC, p4u approved these changes

2024-04-11 16:12 UTC, merged